class FormsTemas {
  +String iconGroup
  +Object tema
  +Array itens
  +Boolean editable
  +Array selectedItems
  +void created()
  +void exibirToast()
  +void postTema()
  +void getTema(String id)
  +void updateTema()
  +void getItens()
}