name: Vue.js CI # Nome do workflow

on: # Definir quando o workflow será executado
  push: # Quando houver um push na branch main
    branches:
      - main
  pull_request: # Quando houver um pull request na branch main
    branches:
      - main

jobs: # Definir o que será executado
  build: # Nome do trabalho "job"
    runs-on: ubuntu-latest # Definir o ambiente onde vai ser executado (ubuntu)

    steps: # Passos
      - name: Checkout repository # Clonar o repositório
        uses: actions/checkout@v2

      - name: Set up Node.js # Configurar o ambiente node
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.1" # Versão do node

      - name: Set up Java JDK # Configurar o Java
        uses: actions/setup-java@v3
        with:
          java-version: "21" # Definir a versão do Java
          distribution: "temurin" # Distribuição

      - name: Install dependencies # Instalar as dependências
        run: npm install # Instalar as dependências

      - name: Install jscpd globally # Instalar jscpd globalmente
        run: npm install -g jscpd # Instalar jscpd globalmente

      - name: Check for code duplication # Verificar duplicação de código nos arquivos especificados
        run: jscpd AluguelFestas/src/views/Temas # Verificar arquivos duplicados na pasta Temas

      - name: Install Graphviz # Instalar Graphviz
        run: sudo apt-get install -y graphviz # Instalar Graphviz

      - name: Download PlantUML # Baixar PlantUML para gerar diagramas
        run: |
          wget https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar -O plantuml.jar # URL dinâmica para sempre pegar a versão mais recente

      - name: Create diagrams directory # Criar o diretório diagrams caso não exista
        run: mkdir -p diagrams # Criar o diretório onde os diagramas serão gerados

      - name: List UML files # Verificar se os arquivos .puml estão presentes
        run: |
          ls -la uml/ # Verificar conteúdo da pasta 'uml'

      - name: Generate UML Diagrams # Gerar diagramas UML com verbose para obter logs detalhados
        run: |
          java -jar plantuml.jar -tpng -o diagrams uml/todos.puml -verbose # Gerar os diagramas

      - name: List diagrams directory # Verificar se os arquivos foram gerados
        run: |
          ls -la diagrams/ # Listar arquivos no diretório diagrams

      - name: Upload UML diagram as artifact # Fazer o upload dos diagramas UML
        uses: actions/upload-artifact@v4.4.3
        with:
          name: uml-diagram
          path: diagrams/*.png # Caminho para os arquivos .png gerados

      - name: Upload production-ready build files # Fazer o upload dos arquivos de build ou deploy
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build
          path: dist # Corrigir para o diretório correto de build do Vue.js
