name: Vue.js CI #nome do workflow

on: #definir quando o workflow será executado
  push: #quando houver um push na branch main
    branches:
      - main
  pull_request: #quando houver um pull request na branch main
    branches:
      - main

jobs: #definir o que sera executado
  build: #nome do trabalho "job", pode ser qualquer um
    runs-on: ubuntu-latest #definir o ambiente onde vai ser executado (ubuntu)

    steps: #passos
      - name: Checkout repository #clonar o repositório
        uses: actions/checkout@v4.2.1 #usar a action checkout

      - name: Set up Node.js #configurar o ambiente node
        uses: actions/setup-node@v4.0.4 #usar a action setup-node
        with:
          node-version: "21.7.1" #versão do node

      - name: Set up Java JDK #configurar o Java
        uses: actions/setup-java@v3 #usar a action setup-java
        with:
          java-version: "21" #definir a versão do Java
          distribution: "temurin" #distribuição

      - name: Install dependencies #instalar as dependencias
        run: npm install #instalar as dependencias

      - name: Install jscpd globally #instalar jscpd globalmente
        run: npm install -g jscpd #instalar jscpd globalmente

      - name: Check for code duplication #verificar duplicação de código nos arquivos especificados
        run: jscpd AluguelFestas/src/views/Temas #verificar arquivos duplicados na pasta Temas

      - name: Install Graphviz #instalar Graphviz
        run: sudo apt-get install graphviz #instalar Graphviz

      - name: Download PlantUML #baixar PlantUML para gerar diagramas
        run: wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar #baixar PlantUML

      - name: List files in UML directory
        run: ls -l uml/

      - name: Generate UML Diagrams
        run: |
          mkdir -p diagrams  # Garantir que o diretório diagrams exista
          java -jar plantuml.jar -tpng -o diagrams uml/todos.puml

      - name: List generated UML diagrams
        run: ls -l diagrams/

      - name: Upload UML Diagrams
        uses: actions/upload-artifact@v4.4.3
        with:
          name: diagrams
          path: diagrams/

      - name: Upload production-ready build files #fazer o upload dos arquivos de build ou deploy
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build
          path: dis
